export {
  ONBOARDING_STEPS,
  SECT_OPTIONS,
  MADHAB_OPTIONS,
  PRAYER_OPTIONS,
  MUSLIM_SINCE_OPTIONS,
  RELIGIOUS_PREFERENCES_TEXT,
  BASIC_INFO_TEXT,
  GENDER_OPTIONS,
  ONBOARDING_ROUTES,
  VALIDATION,
  FILE_UPLOAD,
  IMAGE_COMPRESSION,
  ERROR_MESSAGES,
  SUCCESS_MESSAGES,
  PHOTO_GUIDELINES,
  PHOTO_UPLOAD
} from './onboardingConstants';
