CREATE TABLE IF NOT EXISTS public.weekly_matches (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id TEXT NOT NULL,
  match_user_id TEXT NOT NULL,
  score NUMERIC(5,2) NOT NULL CHECK (score >= 0 AND score <= 100),
  rank INTEGER NOT NULL CHECK (rank >= 1 AND rank <= 5),
  week_start_date DATE NOT NULL,
  compatibility_factors JSONB DEFAULT '{}'::jsonb,
  chaichat_preview JSONB,
  batch_run_id UUID REFERENCES public.batch_run_history(id) ON DELETE SET NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  viewed_at TIMESTAMP WITH TIME ZONE,
  actioned_at TIMESTAMP WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS idx_weekly_matches_user_id_week 
  ON public.weekly_matches(user_id, week_start_date DESC);

CREATE INDEX IF NOT EXISTS idx_weekly_matches_match_user_id 
  ON public.weekly_matches(match_user_id);

CREATE INDEX IF NOT EXISTS idx_weekly_matches_batch_run 
  ON public.weekly_matches(batch_run_id);

CREATE INDEX IF NOT EXISTS idx_weekly_matches_score 
  ON public.weekly_matches(score DESC);

CREATE UNIQUE INDEX IF NOT EXISTS idx_weekly_matches_unique_week 
  ON public.weekly_matches(user_id, match_user_id, week_start_date);

ALTER TABLE public.weekly_matches ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own weekly matches"
ON public.weekly_matches
FOR SELECT
USING (user_id = current_setting('request.jwt.claims', true)::json->>'sub');

CREATE POLICY "Service role can manage all matches"
ON public.weekly_matches
FOR ALL
USING (true)
WITH CHECK (true);

COMMENT ON TABLE public.weekly_matches IS 'Weekly top 5 matches generated by batch processing';
COMMENT ON COLUMN public.weekly_matches.rank IS 'Match rank for the week (1-5, where 1 is best)';
COMMENT ON COLUMN public.weekly_matches.compatibility_factors IS 'JSON breakdown of compatibility scoring factors';
COMMENT ON COLUMN public.weekly_matches.chaichat_preview IS 'Level 1-2 conversation starters';
COMMENT ON COLUMN public.weekly_matches.viewed_at IS 'When user viewed this match';
COMMENT ON COLUMN public.weekly_matches.actioned_at IS 'When user took action (liked, skipped, etc.)';
